### PR TITLE
Fix resource update reconciling, increase log level for users reconciler

### LINKED ISSUE #633: Operator is constantly trying to update OpensearchUser
After we had created users with `OpensearchUser` we noticed that operator is constantly trying to update all created users even when there were no changes.
In operator logs we could see:
```
operator-controller-manager {"level":"info","ts":"2023-10-10T15:18:07.874Z","msg":"Reconciling OpensearchUser","controller":"opensearchuser","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchUs
er","OpensearchUser":{"name":"es-consumer","namespace":"opensearch"},"namespace":"opensearch","name":"es-consumer","reconcileID":"4cd41a78-4a6a-4e3e-9ac4-103e0e08980a","user":{"name":"es-consumer","namespace":"op
ensearch"}}                                                                                                                                                                                                         
operator-controller-manager {"level":"info","ts":"2023-10-10T15:18:08.227Z","msg":"user requires update","controller":"opensearchuser","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchUser","O
pensearchUser":{"name":"es-consumer","namespace":"opensearch"},"namespace":"opensearch","name":"es-consumer","reconcileID":"4cd41a78-4a6a-4e3e-9ac4-103e0e08980a","os_service":"security"}
```

In `OpensearchUser` events we could see that `OpensearchAPIUpdated` counter is constantly increasing:
```
  Normal  OpensearchAPIUpdated  105s (x26 over 7m5s)  user-controller  user updated in opensearch                                                                                                                   
```

Unfortunately, from the [code](https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/opensearch-gateway/services/os_security_service.go#L67) it's not clear why exactly that happens, looks like this `reflect.DeepEqual(user, userResponse[username])` could be the root cause. I think to understand what is not equal between the current user and the response that operator gets there should be some additional logs (e.g. what exactly is different)

Opensearch version 2.3.0
Operator version 2.4.0

### LINKED ISSUE #731: [BUG] `OpensearchIndexTemplate` always requires update
Template:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: all
  namespace: infra
spec:
  opensearchCluster:
    name: opensearch
  name: default_template
  indexPatterns:
    - "*"
  template:
    settings:
      number_of_shards: 6
      number_of_replicas: 0
```

logs:
```
{"level":"info","ts":"2024-02-20T13:36:08.036Z","msg":"Reconciling OpenSearchCluster","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"f0028c11-64b5-48a1-90f1-59d01a9eb1c9","cluster":{"name":"opensearch","namespace":"infra"}}
{"level":"info","ts":"2024-02-20T13:36:08.053Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"f0028c11-64b5-48a1-90f1-59d01a9eb1c9","interface":"transport"}
{"level":"info","ts":"2024-02-20T13:36:08.053Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"f0028c11-64b5-48a1-90f1-59d01a9eb1c9","interface":"http"}
{"level":"info","ts":"2024-02-20T13:36:29.712Z","msg":"Reconciling OpensearchIndexTemplate","controller":"opensearchindextemplate","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchIndexTemplate","OpensearchIndexTemplate":{"name":"all","namespace":"infra"},"namespace":"infra","name":"all","reconcileID":"9703a2eb-0a1a-49b8-bdac-3fe57a3bca5b","indextemplate":{"name":"all","namespace":"infra"}}
{"level":"info","ts":"2024-02-20T13:36:29.759Z","msg":"OpenSearch Index template requires update","controller":"opensearchindextemplate","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchIndexTemplate","OpensearchIndexTemplate":{"name":"all","namespace":"infra"},"namespace":"infra","name":"all","reconcileID":"9703a2eb-0a1a-49b8-bdac-3fe57a3bca5b"}
{"level":"info","ts":"2024-02-20T13:36:38.138Z","msg":"Reconciling OpenSearchCluster","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"c0e46c28-168f-490f-a51f-098815c94bbb","cluster":{"name":"opensearch","namespace":"infra"}}
{"level":"info","ts":"2024-02-20T13:36:38.156Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"c0e46c28-168f-490f-a51f-098815c94bbb","interface":"transport"}
{"level":"info","ts":"2024-02-20T13:36:38.157Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"c0e46c28-168f-490f-a51f-098815c94bbb","interface":"http"}
{"level":"info","ts":"2024-02-20T13:36:59.773Z","msg":"Reconciling OpensearchIndexTemplate","controller":"opensearchindextemplate","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchIndexTemplate","OpensearchIndexTemplate":{"name":"all","namespace":"infra"},"namespace":"infra","name":"all","reconcileID":"6642ef06-985f-43f0-9bbe-746855db23f7","indextemplate":{"name":"all","namespace":"infra"}}
{"level":"info","ts":"2024-02-20T13:36:59.809Z","msg":"OpenSearch Index template requires update","controller":"opensearchindextemplate","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchIndexTemplate","OpensearchIndexTemplate":{"name":"all","namespace":"infra"},"namespace":"infra","name":"all","reconcileID":"6642ef06-985f-43f0-9bbe-746855db23f7"}
{"level":"info","ts":"2024-02-20T13:37:08.269Z","msg":"Reconciling OpenSearchCluster","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"3e68522e-0141-4b27-ad36-be5de48d0412","cluster":{"name":"opensearch","namespace":"infra"}}
{"level":"info","ts":"2024-02-20T13:37:08.289Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"3e68522e-0141-4b27-ad36-be5de48d0412","interface":"transport"}
{"level":"info","ts":"2024-02-20T13:37:08.290Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"infra"},"namespace":"infra","name":"opensearch","reconcileID":"3e68522e-0141-4b27-ad36-be5de48d0412","interface":"http"}
```

And also I see `Generating certificates` each reconcile loop...

docker image: `opensearchproject/opensearch-operator:2.5.1`

### PR DESCRIPTION
**Pull request by evheniyt**
### Description
Fixes #633
Fixes #731 

Based on investigations [here](https://github.com/opensearch-project/opensearch-k8s-operator/issues/633#issuecomment-1941155540) and [here](https://github.com/opensearch-project/opensearch-k8s-operator/issues/731#issuecomment-1962905121) it was found that a discrepancy between `<nil slice>` and `<[] slice>` is causing the operator to constantly update User, Role, IndexTemplate, etc.

Also, the current log level for User reconciles produces too many logs, so increasing its level may be a good idea here.

Because of the issue with comparing `nil` and empty slices, I have replaced `reflect.DeepEqual` with `comp.Equal`. Also, added a helper function that will sort nested json keys in cases when API returns unsorted keys which is casing comparing to  return diff.
### Issues Resolved
Closes #633 
Closes #731

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by evheniyt** [comment]
The reason why tests are broken (and why they were working before) is that in tests `userResponse` `OpendistroSecurityRoles` and `BackendRoles` are nil, [but in reality](https://github.com/opensearch-project/opensearch-k8s-operator/issues/633#issuecomment-1941155540), they are an empty slice
Appreciate it if someone could help with this

**Comment by prudhvigodithi** [comment]
Hey @evheniyt  can you please pull from upstream to fix the failing tests ? Here is the recent PR that can fix the tests https://github.com/opensearch-project/opensearch-k8s-operator/pull/725.
Thanks

**Comment by evheniyt** [comment]
Hi @prudhvigodithi, thank you for your reply. I did a sync with upstream, but I guess in my case the issue is different, please see my comment above that describes why tests are failing for this PR.

**Comment by evheniyt** [comment]
@prudhvigodithi could you please review or add someone from active reviewers?

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @evheniyt for your contribution, the PR LGTM!.
Adding @salyh @pchmielnik @swoehrl-mw @jochenkressin 
@bbarani

**Pull request merged**
