### PR TITLE
Update references to default admin credentials

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Updates docs to inform about changes in security plugin in 2.12.0 that enforces an initial admin password to be set

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/security/issues/3624

**Comment by derek-ho** [comment]
@prudhvigodithi @swoehrl-mw can you folks take a look at this PR and let me know if it is sufficient? I saw a few tests that are using old versions of OpenSearch i.e. 1.x, < 2.12.0 which probably don't need updating, so I mainly fixed up the documentation. Let me know what you think, thanks!

**Comment by DarshitChanpura** [comment]
@prudhvigodithi @swoehrl-mw Can we get reviews on this PR?

**Comment by DarshitChanpura** [comment]
@prudhvigodithi @swoehrl-mw Can we get reviews on this PR?

**Comment by prudhvigodithi** [comment]
Hey @DarshitChanpura a recent PR has been merged https://github.com/opensearch-project/opensearch-k8s-operator/pull/710 and the operator is waiting for a release https://github.com/opensearch-project/opensearch-k8s-operator/issues/709#issuecomment-1915845880. I will get back once we have stable release.
Thanks 
@swoehrl-mw @bbarani

**Comment by DarshitChanpura** [comment]
@prudhvigodithi Is this PR still needed, since #703 is closed?

**Comment by prudhvigodithi** [comment]
No @DarshitChanpura  we can close the PR, thanks @derek-ho.
Adding @bbarani @peterzhuamazon

**Pull request closed without merging**
