### PR TITLE
Fixes OpenSearchISMPolicy crd kind in docs

### PR DESCRIPTION
**Pull request by jojovem**
Minor typo fix for the OpenSearchISMPolicy kind

### Description
Minor typo fix for the OpenSearchISMPolicy kind

### CODE REVIEW

**Comment by jojovem** [comment]
I dont know what is the pattern for CRD naming, but they are using capital S in some and lower case in others:

OpensearchActionGroup
Open**S**earchCluster
OpensearchComponentTemplate
OpensearchIndexTemplate
Open**S**earchISMPolicy
OpensearchRole
OpensearchTenant
OpensearchUserRoleBinding
OpensearchUser

**Comment by prudhvigodithi** [comment]
I would go for capital `S` and once merged I assume this would be a breaking change right ?

**Comment by prudhvigodithi** [comment]
Should we push this change to `v2.6.0` https://github.com/opensearch-project/opensearch-k8s-operator/issues/776 release?
WDYT  @idanl21 @dbason @swoehrl-mw @prudhvigodithi @jochenkressin @pchmielnik @bbarani

**Comment by swoehrl-mw** [comment]
@prudhvigodithi 

> I would go for capital `S` and once merged I assume this would be a breaking change for folks who have applied `OpensearchISMPolicy` right ?

This PR is only a doc change, in the code the capital S is already correct, so no breaking change. That also means it makes no difference if it is merged before or after the release.

**Comment by prudhvigodithi** [comment]
Thanks then can we go ahead with the PR?

**Review by prudhvigodithi — APPROVED** [review]

**Review by swoehrl-mw — APPROVED** [review]

**Pull request merged**
