### PR TITLE
feat: ServiceMonitor add label

### PR DESCRIPTION
**Pull request by loon-hejw**
### Description
ServiceMonitor generates labels based on crd configurationl 

### Issues Resolved
solve issue #572

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks for your contribution @loon-hejw, can you please re-base from main, a recent PR is merged https://github.com/opensearch-project/opensearch-k8s-operator/pull/767 that should fix the CI checks.
Thanks 
@bbarani @swoehrl-mw @salyh

**Comment by swoehrl-mw** [comment]
@loon-hejw Please cleanly rebase your commit on main. You have a few diffs/changes in your PR that are already in main and bloat up the diff.

**Review by swoehrl-mw — CHANGES_REQUESTED** [review]
Code looks good.
* Please make sure the changed CRD yaml is copied into the operator helm chart
* The new field is documented in the userguide and the CRD reference

**Review by swoehrl-mw — CHANGES_REQUESTED** [review]
Please also add the new field to the userguide (https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#adding-opensearch-monitoring-to-your-cluster)

**Comment by loon-hejw** [comment]
@swoehrl-mw  cr

**Comment by loon-hejw** [comment]
@swoehrl-mw re

**Review by swoehrl-mw — APPROVED** [review]

**Pull request merged**
