### PR TITLE
Jenkinsfile bug and prepare for 2.5.0 release

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Jenkinsfile bug and prepare for 2.5.0 release 

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-k8s-operator/issues/709 and https://github.com/opensearch-project/opensearch-k8s-operator/issues/674

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Comment by vipinjn24** [comment]
This image is not available in 
image
Please check

**Comment by vipinjn24** [comment]
also update the versions of supported opensearch that can be installed.

**Comment by vipinjn24** [comment]
alos i see that operator 2.5.0 uses statefulset ondelete strategy, please update the same in docs too.

**Comment by prudhvigodithi** [comment]
Hey @vipinjn24 please check the the workaroud I have posted here https://github.com/opensearch-project/opensearch-k8s-operator/issues/709#issuecomment-1922632388, also to fix this I have a raised a PR for 2.5.1 release.
https://github.com/opensearch-project/opensearch-k8s-operator/pull/716

**Pull request merged**
