### PR TITLE
Invalid CRD types for ISM actions and a nil pointer fix

### PR DESCRIPTION
**Pull request by cthtrifork**
### Description

This fixes a few bugs found while testing the ISMPolicy custom resources.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

### Check List
- [x] Commits are signed per the DCO using --signoff 
- [x] Unittest added for the new/changed functionality and all unit tests are successful
- [x] Customer-visible features documented
- [x] No linter warnings (`make lint`)

If CRDs are changed:
- [x] CRD YAMLs updated (`make manifests`) and also copied into the helm chart
- [x] Changes to CRDs documented

Please refer to the [PR guidelines](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr) before submitting this pull request.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

FYI @IshaGirdhar

### CODE REVIEW

**Comment by cthtrifork** [comment]
I don't know if I should document more. The `readOnly` and `readWrite` have never worked as far I can tell from the code.

Also, I would love to have this in a 2.6.1 patch release

**Comment by swoehrl-mw** [comment]
> I don't know if I should document more. The `readOnly` and `readWrite` have never worked as far I can tell from the code.
> 
> Also, I would love to have this in a 2.6.1 patch release

@cthtrifork As this is an interface change, it cannot be a patch release and must at least be a minor release (e.g. 2.7.0). Also technically speaking this change is incompatible, so would in theory require a new api version. But if you are sure that these two fields never have worked and therefore no one has likely really used them, then I am fine with keeping the api version (it would be way too much hassle to make a new api version just for these two fields).

**Comment by cthtrifork** [comment]
@swoehrl-mw Sounds fair! I have tested it quite thoroughly and I still believe `readOnly` and `readWrite` have never worked, as the api-gateway does not expect them as strings. It throws an error. I could not wrangle the custom resource to work in 2.6.0 regardless of what i tried.
I also vote to keep the same API version.

Is there any release schedule/calendar, ETA for v2.7.0 or similar? I am unsure what to expect and I have people eager to use the ISMPolicies through GitOps. I would like to give them a realistic timeline.

**Comment by cthtrifork** [comment]
I will be happy to do more testing to see if there are other bugs related to the new CRDs, so we don't have too many releases. I would need a guide to make sure I am building the correct/correspondingly image of the operator or I need a release candidate.

**Comment by swoehrl-mw** [comment]
> Is there any release schedule/calendar, ETA for v2.7.0 or similar? I am unsure what to expect and I have people eager to use the ISMPolicies through GitOps. I would like to give them a realistic timeline.

There is no fixed release schedule, we basically release a new version when we feel enough new features have accumulated to make a nice release. Since we just released 2.6.0 I would expect the next release to take a few months.


> I will be happy to do more testing to see if there are other bugs related to the new CRDs, so we don't have too many releases. I would need a guide to make sure I am building the correct/correspondingly image of the operator or I need a release candidate.

That would be great. 
Building and deploying the operator is easy:
```
cd opensearch-operator
IMG=my-image:tag make docker-build  # or if you need the multi-arch image with arm64: make docker-build-multiarch
# push image to your registry
cd ..
helm install opensearch-operator charts/opensearch-operator --set manager.image.repository=my-image --set manager.image.tag=tag --set manager.image.pullPolicy=IfNotPresent
```

**Comment by cthtrifork** [comment]
@swoehrl-mw Great. I got it working. Can we merge this to main and I will continue testing on the main branch in my fork.

**Comment by cthtrifork** [comment]
> Code looks good. Only thing missing is copying the changed CRD yaml into the operator helm chart.

Ah thanks. Done!

**Review by swoehrl-mw — APPROVED** [review]

**Pull request merged**
