### PR TITLE
Add warning about cert expiration

### PR DESCRIPTION
**Pull request by trondhindenes**
### Description
This PR adds a warning to make users aware of the 1-year validity time of operator-generated certificates. When documentation for renewing the certificates is available, it would be good to add link to it from here.

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @trondhindenes can you please pull from upstream to fix the failing tests ? Here is the recent PR that can fix the tests https://github.com/opensearch-project/opensearch-k8s-operator/pull/725.
Thanks

**Comment by trondhindenes** [comment]
> Hey @trondhindenes can you please pull from upstream to fix the failing tests ? Here is the recent PR that can fix the tests #725. Thanks

thanks! pulled in an updated main branch and rebased now.

**Comment by prudhvigodithi** [comment]
Hey @trondhindenes I dont see its rebased properly as I see the same change again part of this PR [.github/workflows/functional-tests.yaml.](https://github.com/opensearch-project/opensearch-k8s-operator/pull/729/files).

**Comment by prudhvigodithi** [comment]
Thanks @trondhindenes 
Adding @bbarani @jochenkressin @pchmielnik @salyh @swoehrl-mw

**Pull request merged**
