### PR TITLE
Adding pluginsList and keystore fields to BootstrapConfig

### PR DESCRIPTION
**Pull request by szamuboy**
### Description

This change adds the `bootstrap.keystore` and `bootstrap.pluginsList` fields to the OpenSearchCluster custom resource.

This changes how the bootstrap pod is generated. The behavior is the same as with the `general.keystore` and `general.pluginsList` fields. 

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-k8s-operator/issues/430 and https://github.com/opensearch-project/opensearch-k8s-operator/issues/639.

### Check List
- [x] Commits are signed per the DCO using --signoff 
- [x] Unittest added for the new/changed functionality and all unit tests are successful
- [x] Customer-visible features documented
- [x] No linter warnings (`make lint`)

If CRDs are changed:
- [x] CRD YAMLs updated (`make manifests`) and also copied into the helm chart
- [x] Changes to CRDs documented

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @szamuboy thanks for the contribution, the change looks good, can you please fix the failing CI checks and we can merge this.
Thank you 
@getsaurabh02 @swoehrl-mw

**Comment by prudhvigodithi** [comment]
Thanks @szamuboy, this looks good to me, @swoehrl-mw can you please provide your thoughts on the PR?
@salyh @pchmielnik @jochenkressin @getsaurabh02

**Comment by szamuboy** [comment]
Thank you @prudhvigodithi for the review. I look forward to the comments.

**Review by swoehrl-mw — APPROVED** [review]
LGTM

**Pull request merged**
