### PR TITLE
opensearchcluster spec add Job  resource config  

### LINKED ISSUE #678: [BUG] cluster can not be created when ResourceQuota  set
Hi friends
When I create a cluster under a namespace with **ResourceQuota** set, I found that some resources cannot be set with request and limit, resulting in creation failure.
ResourceQuota yaml：
```apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-middleware-3968
  namespace: project-middleware-3968
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 10Gi
    requests.storage: 10Gi
status:
  hard:
    limits.cpu: "10"
    limits.memory: 10Gi
    requests.storage: 10Gi
  used:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.storage: 7Gi
```
opensearch  statefulset describe like：
```
Events:
  Type     Reason            Age                             From                    Message
  ----     ------            ----                            ----                    -------
  Normal   SuccessfulCreate  <invalid>                       statefulset-controller  create Claim data-opensearch-sample-masters-0 Pod opensearch-sample-masters-0 in StatefulSet opensearch-sample-masters success
  Warning  FailedCreate      <invalid> (x14 over <invalid>)  statefulset-controller  create Pod opensearch-sample-masters-0 in StatefulSet opensearch-sample-masters failed error: pods "opensearch-sample-masters-0" is forbidden: failed quota: project-middleware-3968: must specify limits.cpu,limits.memory
```

I reviewed the source code and found that the init container named **"init"** can inherit the resource settings from Spec.InitHelper.Resources. However, the init containers named **"init-sysctl"** and **"keystore"** cannot inherit the resource settings.
In addition to that, I also found that all generated jobs, such as **SnapshotRepoconfigUpdateJob** and **SecurityconfigUpdateJob**, cannot have resource settings applied to them.

Below are my modifications:

1. All init containers can inherit the settings from Spec.InitHelper.Resources.
2. Add a Job field to Spec and configure all jobs with settings such as Resource, NodeSelector, Label, etc. as shown below:
  ```
type ClusterSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	General    GeneralConfig    `json:"general,omitempty"`
	ConfMgmt   ConfMgmt         `json:"confMgmt,omitempty"`
	Bootstrap  BootstrapConfig  `json:"bootstrap,omitempty"`
	Dashboards DashboardsConfig `json:"dashboards,omitempty"`
	Security   *Security        `json:"security,omitempty"`
	NodePools  []NodePool       `json:"nodePools"`
	InitHelper InitHelperConfig `json:"initHelper,omitempty"`
	Job        JobConfig        `json:"job,omitempty"`
}
type JobConfig struct {
	Resources    corev1.ResourceRequirements `json:"resources,omitempty"`
	NodeSelector map[string]string           `json:"nodeSelector,omitempty"`
	Affinity     *corev1.Affinity            `json:"affinity,omitempty"`
	Labels       map[string]string           `json:"labels,omitempty"`
	Annotations  map[string]string           `json:"annotations,omitempty"`
}
```

### PR DESCRIPTION
**Pull request by wangshulei098**
add job config to support resourcequota

### Description

1. All init containers can inherit the settings from Spec.InitHelper.Resources.
2. Add a Job field to Spec and configure all jobs with settings such as Resource, NodeSelector, Label, Affinity

### Issues Resolved
Fixes #678

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @wangshulei098 thanks for your contribution, we can ship this, is it possible to add some unit tests, also please fix the conflicts.
Thank you 
Adding @salyh @pchmielnik @swoehrl-mw @jochenkressin
@bbarani

**Comment by wangshulei098** [comment]
> Hey @wangshulei098 thanks for your contribution, we can ship this, is it possible to add some unit tests, also please fix the conflicts. Thank you Adding @salyh @pchmielnik @swoehrl-mw @jochenkressin @bbarani

Hey， The conflict has been resolved and the unit tests have been added, please approve to proceed，thanks

**Comment by wangshulei098** [comment]
> Hi @wangshulei098 thanky you but I still see a confilct in "opensearch-operator/pkg/builders/cluster.go". Please re-base from main.

Hey @salyh ，The conflict resulting from merging new commits has been resolved. Please approve at your earliest convenience，thanks

**Comment by swoehrl-mw** [comment]
This PR has overlap with #628, need to make sure they do not conflict and do not solve the same thing 

@salyh @prudhvigodithi

**Comment by wangshulei098** [comment]
> This PR has overlap with #628, need to make sure they do not conflict and do not solve the same thing
> 
> @salyh @prudhvigodithi

This PR resolves  the issue of being unable to deploy applications, including initcontainers and some jobs, after setting resourcequotas. However, The PR associated with #628 fails to address this issue.
Please compare the related PRs and address this issue promptly. Thanks

**Comment by prudhvigodithi** [comment]
As mentioned I'm ok to move forward with this unless @salyh @swoehrl-mw has any objections, @wangshulei098 can you update the readme with examples as well so folks understand and know `resourcequota` exists. We can target this in [v2.6.0](https://github.com/opensearch-project/opensearch-k8s-operator/issues/776).
Thanks

**Comment by wangshulei098** [comment]
> As mentioned I'm ok to move forward with this unless @salyh @swoehrl-mw has any objections, @wangshulei098 can you update the readme with examples as well so folks understand and know `resourcequota` exists. We can target this in [v2.6.0](https://github.com/opensearch-project/opensearch-k8s-operator/issues/776). Thanks

Okay, I have updated the readme and added the feature of supporting namespace ResourceQuota.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Adding  @salyh @swoehrl-mw @jochenkressin @pchmielnik to please check this PR.
Thanks

**Comment by wangshulei098** [comment]
@salyh @swoehrl-mw @jochenkressin @pchmielnik   please help to check this PR. thanks

**Comment by wangshulei098** [comment]
another pr has coverd all features of this PR。 close  #678

**Pull request closed without merging**
