### PR TITLE
feat: add masked field to role

### LINKED ISSUE #765: [FEATURE] Add maskedFields to OpensearchRole
To support [field masking](https://opensearch.org/docs/latest/security/access-control/field-masking/) it is necessary to add `maskedFields` to the `indexPermissions` within the `OpensearchRole` resource.

Example OpensearchRole:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: mask
spec:
  opensearchCluster:
    name: test
  name: mask
  indexPermissions:
    - indexPatterns:
        - "*"
      allowedActions:
        - "read"
      maskedFields:
        - "message"
```

### PR DESCRIPTION
**Pull request by cgroschupp**
### Description
Add masked fields to OpensearchRole

Close #765

### CODE REVIEW

**Comment by cgroschupp** [comment]
@prudhvigodithi done

**Comment by cgroschupp** [comment]
@salyh i found the issue with envtest and golang 1.19. i changed envtest to release-16

**Comment by cgroschupp** [comment]
@salyh forget my last comment, i rebased by branch to use golang 1.22

**Comment by prudhvigodithi** [comment]
LGTM, @swoehrl-mw or @salyh WDYT?

**Review by swoehrl-mw — CHANGES_REQUESTED** [review]
* New field needs to be documented in `docs/designs/crd.md`
* The extended CRD needs to be copied into the operator helm chart

**Comment by cgroschupp** [comment]
@swoehrl-mw  `docs/designs/crd.md` is very outdated. Maybe it is better to generate it, see commit: https://github.com/opensearch-project/opensearch-k8s-operator/pull/762/commits/9467df042314b77de8c59ee2b27b35028181c0e8

**Comment by swoehrl-mw** [comment]
> `docs/designs/crd.md` is very outdated. Maybe it is better to generate it, see commit: [c16cc73](https://github.com/opensearch-project/opensearch-k8s-operator/commit/c16cc732d254060a6cca5e81333a2274099a0d4a)

@cgroschupp 
A good idea, but this should be properly introduced in a separate PR that makes sure all parts of the old reference are in code comments and removes the old file. And ideally it should introduce a new automated PR check that the docs have been generated.

**Comment by cgroschupp** [comment]
@swoehrl-mw i have updated the tests and copied the crds to the helm chart directory. for the api docs generation task i will create a new pr.

**Review by swoehrl-mw — APPROVED** [review]

**Comment by swoehrl-mw** [comment]
@salyh Can you please also approve and then merge (seems merge is only allowed after all reviewers who have requested changes have approved)?

**Review by salyh — APPROVED** [review]

**Pull request merged**
